version: "3.9"
services:
  web:
    image: php:8.2-apache
    container_name: php8.2-apache
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
    platform: linux/amd64 # Add this line for x86 support
  db:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql:/var/lib/mysql
    platform: linux/amd64 # Add this line for x86 support
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    platform: linux/amd64 # Add this line for x86 support
